//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLBBWS.eDMSTTMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/DocufloSDK/Service1", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataProfileResult", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    [System.SerializableAttribute()]
    public partial class DataProfileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLBBWS.eDMSTTMS.DataColumn[] Arr_DataValueField;
        
        private long VerIDField;
        
        private long ProfileIDField;
        
        private long DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        private int TotalRecFoundField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HLBBWS.eDMSTTMS.DataColumn[] Arr_DataValue {
            get {
                return this.Arr_DataValueField;
            }
            set {
                if ((object.ReferenceEquals(this.Arr_DataValueField, value) != true)) {
                    this.Arr_DataValueField = value;
                    this.RaisePropertyChanged("Arr_DataValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long VerID {
            get {
                return this.VerIDField;
            }
            set {
                if ((this.VerIDField.Equals(value) != true)) {
                    this.VerIDField = value;
                    this.RaisePropertyChanged("VerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((this.ProfileIDField.Equals(value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((this.DocIDField.Equals(value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TotalRecFound {
            get {
                return this.TotalRecFoundField;
            }
            set {
                if ((this.TotalRecFoundField.Equals(value) != true)) {
                    this.TotalRecFoundField = value;
                    this.RaisePropertyChanged("TotalRecFound");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataColumn", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    [System.SerializableAttribute()]
    public partial class DataColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Col_DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Col_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Col_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Col_Desc {
            get {
                return this.Col_DescField;
            }
            set {
                if ((object.ReferenceEquals(this.Col_DescField, value) != true)) {
                    this.Col_DescField = value;
                    this.RaisePropertyChanged("Col_Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProfileValue {
            get {
                return this.ProfileValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileValueField, value) != true)) {
                    this.ProfileValueField = value;
                    this.RaisePropertyChanged("ProfileValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Col_ID {
            get {
                return this.Col_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Col_IDField, value) != true)) {
                    this.Col_IDField = value;
                    this.RaisePropertyChanged("Col_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Col_Name {
            get {
                return this.Col_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Col_NameField, value) != true)) {
                    this.Col_NameField = value;
                    this.RaisePropertyChanged("Col_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/DocufloSDK/Service1", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profiles", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    [System.SerializableAttribute()]
    public partial class Profiles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int profileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int profileID {
            get {
                return this.profileIDField;
            }
            set {
                if ((this.profileIDField.Equals(value) != true)) {
                    this.profileIDField = value;
                    this.RaisePropertyChanged("profileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string profileName {
            get {
                return this.profileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.profileNameField, value) != true)) {
                    this.profileNameField = value;
                    this.RaisePropertyChanged("profileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileField", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    [System.SerializableAttribute()]
    public partial class ProfileField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int colIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colDataTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int colID {
            get {
                return this.colIDField;
            }
            set {
                if ((this.colIDField.Equals(value) != true)) {
                    this.colIDField = value;
                    this.RaisePropertyChanged("colID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string colName {
            get {
                return this.colNameField;
            }
            set {
                if ((object.ReferenceEquals(this.colNameField, value) != true)) {
                    this.colNameField = value;
                    this.RaisePropertyChanged("colName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string colDesc {
            get {
                return this.colDescField;
            }
            set {
                if ((object.ReferenceEquals(this.colDescField, value) != true)) {
                    this.colDescField = value;
                    this.RaisePropertyChanged("colDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string colDataType {
            get {
                return this.colDataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.colDataTypeField, value) != true)) {
                    this.colDataTypeField = value;
                    this.RaisePropertyChanged("colDataType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1", ConfigurationName="eDMSTTMS.DocufloSDKSoap")]
    public interface DocufloSDKSoap {
        
        // CODEGEN: Generating message contract since element name FileContent from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Export", ReplyAction="*")]
        HLBBWS.eDMSTTMS.ExportResponse Export(HLBBWS.eDMSTTMS.ExportRequest request);
        
        // CODEGEN: Generating message contract since element name strCriteria from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Search", ReplyAction="*")]
        HLBBWS.eDMSTTMS.SearchResponse Search(HLBBWS.eDMSTTMS.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name SearchByDocIDResult from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/SearchByDocID", ReplyAction="*")]
        HLBBWS.eDMSTTMS.SearchByDocIDResponse SearchByDocID(HLBBWS.eDMSTTMS.SearchByDocIDRequest request);
        
        // CODEGEN: Generating message contract since element name profile_name from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/ProfileSearch", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataProfileResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataProfileResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.Profiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.Profiles[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ProfileField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ProfileField[]))]
        HLBBWS.eDMSTTMS.ProfileSearchResponse ProfileSearch(HLBBWS.eDMSTTMS.ProfileSearchRequest request);
        
        // CODEGEN: Generating message contract since element name FileName from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Download", ReplyAction="*")]
        HLBBWS.eDMSTTMS.DownloadResponse Download(HLBBWS.eDMSTTMS.DownloadRequest request);
        
        // CODEGEN: Generating message contract since element name profile_name from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/UpdateTargetProfileValue", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataProfileResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataProfileResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.DataColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.Profiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.Profiles[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ProfileField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HLBBWS.eDMSTTMS.ProfileField[]))]
        HLBBWS.eDMSTTMS.UpdateTargetProfileValueResponse UpdateTargetProfileValue(HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteDocumentResult from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/DeleteDocument", ReplyAction="*")]
        HLBBWS.eDMSTTMS.DeleteDocumentResponse DeleteDocument(HLBBWS.eDMSTTMS.DeleteDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Login", ReplyAction="*")]
        HLBBWS.eDMSTTMS.LoginResponse Login(HLBBWS.eDMSTTMS.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name LoadProfilesResult from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/LoadProfiles", ReplyAction="*")]
        HLBBWS.eDMSTTMS.LoadProfilesResponse LoadProfiles(HLBBWS.eDMSTTMS.LoadProfilesRequest request);
        
        // CODEGEN: Generating message contract since element name LoadProfileFieldResult from namespace http://tempuri.org/DocufloSDK/Service1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/LoadProfileField", ReplyAction="*")]
        HLBBWS.eDMSTTMS.LoadProfileFieldResponse LoadProfileField(HLBBWS.eDMSTTMS.LoadProfileFieldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Export", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.ExportRequestBody Body;
        
        public ExportRequest() {
        }
        
        public ExportRequest(HLBBWS.eDMSTTMS.ExportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ExportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strProfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public HLBBWS.eDMSTTMS.ArrayOfString arrProfileValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userID;
        
        public ExportRequestBody() {
        }
        
        public ExportRequestBody(byte[] FileContent, string strFileName, string strProfile, string strFolderName, HLBBWS.eDMSTTMS.ArrayOfString arrProfileValue, string userID) {
            this.FileContent = FileContent;
            this.strFileName = strFileName;
            this.strProfile = strProfile;
            this.strFolderName = strFolderName;
            this.arrProfileValue = arrProfileValue;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.ExportResponseBody Body;
        
        public ExportResponse() {
        }
        
        public ExportResponse(HLBBWS.eDMSTTMS.ExportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ExportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportResult;
        
        public ExportResponseBody() {
        }
        
        public ExportResponseBody(string ExportResult) {
            this.ExportResult = ExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(HLBBWS.eDMSTTMS.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCriteria;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string strCriteria) {
            this.strCriteria = strCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(HLBBWS.eDMSTTMS.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HLBBWS.eDMSTTMS.DataProfileResult[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(HLBBWS.eDMSTTMS.DataProfileResult[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByDocIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByDocID", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.SearchByDocIDRequestBody Body;
        
        public SearchByDocIDRequest() {
        }
        
        public SearchByDocIDRequest(HLBBWS.eDMSTTMS.SearchByDocIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchByDocIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int profileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long docID;
        
        public SearchByDocIDRequestBody() {
        }
        
        public SearchByDocIDRequestBody(int profileID, long docID) {
            this.profileID = profileID;
            this.docID = docID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByDocIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByDocIDResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.SearchByDocIDResponseBody Body;
        
        public SearchByDocIDResponse() {
        }
        
        public SearchByDocIDResponse(HLBBWS.eDMSTTMS.SearchByDocIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchByDocIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HLBBWS.eDMSTTMS.DataProfileResult[] SearchByDocIDResult;
        
        public SearchByDocIDResponseBody() {
        }
        
        public SearchByDocIDResponseBody(HLBBWS.eDMSTTMS.DataProfileResult[] SearchByDocIDResult) {
            this.SearchByDocIDResult = SearchByDocIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProfileSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProfileSearch", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.ProfileSearchRequestBody Body;
        
        public ProfileSearchRequest() {
        }
        
        public ProfileSearchRequest(HLBBWS.eDMSTTMS.ProfileSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ProfileSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profile_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HLBBWS.eDMSTTMS.ArrayOfAnyType column_names;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HLBBWS.eDMSTTMS.ArrayOfAnyType column_keywords;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string error_msg;
        
        public ProfileSearchRequestBody() {
        }
        
        public ProfileSearchRequestBody(string profile_name, HLBBWS.eDMSTTMS.ArrayOfAnyType column_names, HLBBWS.eDMSTTMS.ArrayOfAnyType column_keywords, string error_msg) {
            this.profile_name = profile_name;
            this.column_names = column_names;
            this.column_keywords = column_keywords;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProfileSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProfileSearchResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.ProfileSearchResponseBody Body;
        
        public ProfileSearchResponse() {
        }
        
        public ProfileSearchResponse(HLBBWS.eDMSTTMS.ProfileSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ProfileSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HLBBWS.eDMSTTMS.DataProfileResult[] ProfileSearchResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error_msg;
        
        public ProfileSearchResponseBody() {
        }
        
        public ProfileSearchResponseBody(HLBBWS.eDMSTTMS.DataProfileResult[] ProfileSearchResult, string error_msg) {
            this.ProfileSearchResult = ProfileSearchResult;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Download", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.DownloadRequestBody Body;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(HLBBWS.eDMSTTMS.DownloadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DownloadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long VerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long DocProfileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short FileType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] FileContent;
        
        public DownloadRequestBody() {
        }
        
        public DownloadRequestBody(long VerID, long DocProfileID, short FileType, string FileName, byte[] FileContent) {
            this.VerID = VerID;
            this.DocProfileID = DocProfileID;
            this.FileType = FileType;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.DownloadResponseBody Body;
        
        public DownloadResponse() {
        }
        
        public DownloadResponse(HLBBWS.eDMSTTMS.DownloadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DownloadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownloadResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] FileContent;
        
        public DownloadResponseBody() {
        }
        
        public DownloadResponseBody(string DownloadResult, string FileName, byte[] FileContent) {
            this.DownloadResult = DownloadResult;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTargetProfileValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTargetProfileValue", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequestBody Body;
        
        public UpdateTargetProfileValueRequest() {
        }
        
        public UpdateTargetProfileValueRequest(HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class UpdateTargetProfileValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long docID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string profile_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string base_column_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object base_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string target_column_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public object target_value;
        
        public UpdateTargetProfileValueRequestBody() {
        }
        
        public UpdateTargetProfileValueRequestBody(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, object target_value) {
            this.docID = docID;
            this.profile_name = profile_name;
            this.base_column_name = base_column_name;
            this.base_value = base_value;
            this.target_column_name = target_column_name;
            this.target_value = target_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTargetProfileValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTargetProfileValueResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.UpdateTargetProfileValueResponseBody Body;
        
        public UpdateTargetProfileValueResponse() {
        }
        
        public UpdateTargetProfileValueResponse(HLBBWS.eDMSTTMS.UpdateTargetProfileValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class UpdateTargetProfileValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateTargetProfileValueResult;
        
        public UpdateTargetProfileValueResponseBody() {
        }
        
        public UpdateTargetProfileValueResponseBody(string UpdateTargetProfileValueResult) {
            this.UpdateTargetProfileValueResult = UpdateTargetProfileValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocument", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.DeleteDocumentRequestBody Body;
        
        public DeleteDocumentRequest() {
        }
        
        public DeleteDocumentRequest(HLBBWS.eDMSTTMS.DeleteDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DeleteDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long docID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long profileID;
        
        public DeleteDocumentRequestBody() {
        }
        
        public DeleteDocumentRequestBody(long docID, long profileID) {
            this.docID = docID;
            this.profileID = profileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocumentResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.DeleteDocumentResponseBody Body;
        
        public DeleteDocumentResponse() {
        }
        
        public DeleteDocumentResponse(HLBBWS.eDMSTTMS.DeleteDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DeleteDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDocumentResult;
        
        public DeleteDocumentResponseBody() {
        }
        
        public DeleteDocumentResponseBody(string DeleteDocumentResult) {
            this.DeleteDocumentResult = DeleteDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(HLBBWS.eDMSTTMS.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userID;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userName, string userPassword, string userID) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(HLBBWS.eDMSTTMS.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userID;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult, string userID) {
            this.LoginResult = LoginResult;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfiles", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoadProfilesRequestBody Body;
        
        public LoadProfilesRequest() {
        }
        
        public LoadProfilesRequest(HLBBWS.eDMSTTMS.LoadProfilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadProfilesRequestBody {
        
        public LoadProfilesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfilesResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoadProfilesResponseBody Body;
        
        public LoadProfilesResponse() {
        }
        
        public LoadProfilesResponse(HLBBWS.eDMSTTMS.LoadProfilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HLBBWS.eDMSTTMS.Profiles[] LoadProfilesResult;
        
        public LoadProfilesResponseBody() {
        }
        
        public LoadProfilesResponseBody(HLBBWS.eDMSTTMS.Profiles[] LoadProfilesResult) {
            this.LoadProfilesResult = LoadProfilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfileFieldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfileField", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoadProfileFieldRequestBody Body;
        
        public LoadProfileFieldRequest() {
        }
        
        public LoadProfileFieldRequest(HLBBWS.eDMSTTMS.LoadProfileFieldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfileFieldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intProfileID;
        
        public LoadProfileFieldRequestBody() {
        }
        
        public LoadProfileFieldRequestBody(int intProfileID) {
            this.intProfileID = intProfileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfileFieldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfileFieldResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public HLBBWS.eDMSTTMS.LoadProfileFieldResponseBody Body;
        
        public LoadProfileFieldResponse() {
        }
        
        public LoadProfileFieldResponse(HLBBWS.eDMSTTMS.LoadProfileFieldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfileFieldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HLBBWS.eDMSTTMS.ProfileField[] LoadProfileFieldResult;
        
        public LoadProfileFieldResponseBody() {
        }
        
        public LoadProfileFieldResponseBody(HLBBWS.eDMSTTMS.ProfileField[] LoadProfileFieldResult) {
            this.LoadProfileFieldResult = LoadProfileFieldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocufloSDKSoapChannel : HLBBWS.eDMSTTMS.DocufloSDKSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocufloSDKSoapClient : System.ServiceModel.ClientBase<HLBBWS.eDMSTTMS.DocufloSDKSoap>, HLBBWS.eDMSTTMS.DocufloSDKSoap {
        
        public DocufloSDKSoapClient() {
        }
        
        public DocufloSDKSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocufloSDKSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocufloSDKSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocufloSDKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.ExportResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.Export(HLBBWS.eDMSTTMS.ExportRequest request) {
            return base.Channel.Export(request);
        }

        public string Export(byte[] FileContent, string strFileName, string strProfile, string strFolderName, HLBBWS.eDMSTTMS.ArrayOfString arrProfileValue, string userID) 
        //public string Export(byte[] FileContent, string strFileName, string strProfile, string strFolderName, string[] arrProfileValue, string userID)
        {
            HLBBWS.eDMSTTMS.ExportRequest inValue = new HLBBWS.eDMSTTMS.ExportRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.ExportRequestBody();
            inValue.Body.FileContent = FileContent;
            inValue.Body.strFileName = strFileName;
            inValue.Body.strProfile = strProfile;
            inValue.Body.strFolderName = strFolderName;
            inValue.Body.arrProfileValue = arrProfileValue;
            inValue.Body.userID = userID;
            HLBBWS.eDMSTTMS.ExportResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).Export(inValue);
            return retVal.Body.ExportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.SearchResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.Search(HLBBWS.eDMSTTMS.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public HLBBWS.eDMSTTMS.DataProfileResult[] Search(string strCriteria) {
            HLBBWS.eDMSTTMS.SearchRequest inValue = new HLBBWS.eDMSTTMS.SearchRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.SearchRequestBody();
            inValue.Body.strCriteria = strCriteria;
            HLBBWS.eDMSTTMS.SearchResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.SearchByDocIDResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.SearchByDocID(HLBBWS.eDMSTTMS.SearchByDocIDRequest request) {
            return base.Channel.SearchByDocID(request);
        }
        
        public HLBBWS.eDMSTTMS.DataProfileResult[] SearchByDocID(int profileID, long docID) {
            HLBBWS.eDMSTTMS.SearchByDocIDRequest inValue = new HLBBWS.eDMSTTMS.SearchByDocIDRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.SearchByDocIDRequestBody();
            inValue.Body.profileID = profileID;
            inValue.Body.docID = docID;
            HLBBWS.eDMSTTMS.SearchByDocIDResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).SearchByDocID(inValue);
            return retVal.Body.SearchByDocIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.ProfileSearchResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.ProfileSearch(HLBBWS.eDMSTTMS.ProfileSearchRequest request) {
            return base.Channel.ProfileSearch(request);
        }
        
        public HLBBWS.eDMSTTMS.DataProfileResult[] ProfileSearch(string profile_name, HLBBWS.eDMSTTMS.ArrayOfAnyType column_names, HLBBWS.eDMSTTMS.ArrayOfAnyType column_keywords, ref string error_msg) {
            HLBBWS.eDMSTTMS.ProfileSearchRequest inValue = new HLBBWS.eDMSTTMS.ProfileSearchRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.ProfileSearchRequestBody();
            inValue.Body.profile_name = profile_name;
            inValue.Body.column_names = column_names;
            inValue.Body.column_keywords = column_keywords;
            inValue.Body.error_msg = error_msg;
            HLBBWS.eDMSTTMS.ProfileSearchResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).ProfileSearch(inValue);
            error_msg = retVal.Body.error_msg;
            return retVal.Body.ProfileSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.DownloadResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.Download(HLBBWS.eDMSTTMS.DownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public string Download(long VerID, long DocProfileID, short FileType, ref string FileName, ref byte[] FileContent) {
            HLBBWS.eDMSTTMS.DownloadRequest inValue = new HLBBWS.eDMSTTMS.DownloadRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.DownloadRequestBody();
            inValue.Body.VerID = VerID;
            inValue.Body.DocProfileID = DocProfileID;
            inValue.Body.FileType = FileType;
            inValue.Body.FileName = FileName;
            inValue.Body.FileContent = FileContent;
            HLBBWS.eDMSTTMS.DownloadResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).Download(inValue);
            FileName = retVal.Body.FileName;
            FileContent = retVal.Body.FileContent;
            return retVal.Body.DownloadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.UpdateTargetProfileValueResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.UpdateTargetProfileValue(HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequest request) {
            return base.Channel.UpdateTargetProfileValue(request);
        }
        
        public string UpdateTargetProfileValue(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, object target_value) {
            HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequest inValue = new HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.UpdateTargetProfileValueRequestBody();
            inValue.Body.docID = docID;
            inValue.Body.profile_name = profile_name;
            inValue.Body.base_column_name = base_column_name;
            inValue.Body.base_value = base_value;
            inValue.Body.target_column_name = target_column_name;
            inValue.Body.target_value = target_value;
            HLBBWS.eDMSTTMS.UpdateTargetProfileValueResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).UpdateTargetProfileValue(inValue);
            return retVal.Body.UpdateTargetProfileValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.DeleteDocumentResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.DeleteDocument(HLBBWS.eDMSTTMS.DeleteDocumentRequest request) {
            return base.Channel.DeleteDocument(request);
        }
        
        public string DeleteDocument(long docID, long profileID) {
            HLBBWS.eDMSTTMS.DeleteDocumentRequest inValue = new HLBBWS.eDMSTTMS.DeleteDocumentRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.DeleteDocumentRequestBody();
            inValue.Body.docID = docID;
            inValue.Body.profileID = profileID;
            HLBBWS.eDMSTTMS.DeleteDocumentResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).DeleteDocument(inValue);
            return retVal.Body.DeleteDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.LoginResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.Login(HLBBWS.eDMSTTMS.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string userName, string userPassword, ref string userID) {
            HLBBWS.eDMSTTMS.LoginRequest inValue = new HLBBWS.eDMSTTMS.LoginRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userID = userID;
            HLBBWS.eDMSTTMS.LoginResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).Login(inValue);
            userID = retVal.Body.userID;
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.LoadProfilesResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.LoadProfiles(HLBBWS.eDMSTTMS.LoadProfilesRequest request) {
            return base.Channel.LoadProfiles(request);
        }
        
        public HLBBWS.eDMSTTMS.Profiles[] LoadProfiles() {
            HLBBWS.eDMSTTMS.LoadProfilesRequest inValue = new HLBBWS.eDMSTTMS.LoadProfilesRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.LoadProfilesRequestBody();
            HLBBWS.eDMSTTMS.LoadProfilesResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).LoadProfiles(inValue);
            return retVal.Body.LoadProfilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.eDMSTTMS.LoadProfileFieldResponse HLBBWS.eDMSTTMS.DocufloSDKSoap.LoadProfileField(HLBBWS.eDMSTTMS.LoadProfileFieldRequest request) {
            return base.Channel.LoadProfileField(request);
        }
        
        public HLBBWS.eDMSTTMS.ProfileField[] LoadProfileField(int intProfileID) {
            HLBBWS.eDMSTTMS.LoadProfileFieldRequest inValue = new HLBBWS.eDMSTTMS.LoadProfileFieldRequest();
            inValue.Body = new HLBBWS.eDMSTTMS.LoadProfileFieldRequestBody();
            inValue.Body.intProfileID = intProfileID;
            HLBBWS.eDMSTTMS.LoadProfileFieldResponse retVal = ((HLBBWS.eDMSTTMS.DocufloSDKSoap)(this)).LoadProfileField(inValue);
            return retVal.Body.LoadProfileFieldResult;
        }

    }
}
